=== Phelliks/TP1_230000313_IntegracaoDeSistemas/Servidor/XSD/livros_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Define a estrutura do arquivo XML que armazena os livros -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="livros">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="livro" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="autor" type="xs:string"/>
              <xs:element name="preco" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Phelliks/TP1_230000313_IntegracaoDeSistemas/livros.xml
<?xml version='1.0' encoding='utf-8'?>
<livros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Servidor/Soap/livros_schema.xsd"><livro><nome>Teste</nome><autor>Teste</autor><preco>1.0</preco></livro><livro><nome>Teste</nome><autor>Teste</autor><preco>1.0</preco></livro><livro><nome>a</nome><autor>Teste</autor><preco>1.0</preco></livro></livros>
